# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('born', models.DateTimeField(verbose_name='born date')),
                ('cap', models.DecimalField(decimal_places=5, max_digits=5)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=254)),
                ('card', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data', models.DateTimeField(verbose_name='processing date')),
                ('cost', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('person', models.ManyToManyField(null=True, to='gestionaleapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('occasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionaleapp.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionaleapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(to='gestionaleapp.Person'),
        ),
    ]
