# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0006_auto_20170320_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionaleapp.Event'),
        ),
    ]
