# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0007_auto_20170320_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='person',
            field=models.ManyToManyField(blank=True, to='gestionaleapp.Person'),
        ),
    ]
