# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0009_auto_20170320_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='processing',
            name='person',
        ),
        migrations.AddField(
            model_name='processing',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionaleapp.Person'),
        ),
    ]
