# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0010_auto_20170322_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(max_length=11),
        ),
    ]
