# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0011_auto_20170322_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
