# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0013_auto_20170419_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.DateField(verbose_name='born date'),
        ),
    ]
