# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionaleapp', '0014_auto_20170419_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_association',
            field=models.DateField(default=None, verbose_name='Data associazione'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.DateField(verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cap',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.IntegerField(max_length=5, unique=True, verbose_name='Tessera'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.BigIntegerField(max_length=15, verbose_name='Cellulare'),
        ),
    ]
