# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('surname', models.CharField(max_length=50, verbose_name='Cognome')),
                ('born', models.DateField(verbose_name='Data di nascita')),
                ('cap', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Campo non valido', regex='^\\d{5}$')], verbose_name='CAP')),
                ('telephone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Numero di telefono non valido', regex='^\\+\\d{8,15}$')], verbose_name='Cellulare')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('card', models.CharField(default='VRFL', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Campo non valido', regex='^\\d{5}$')], verbose_name='Tessera')),
                ('first_association', models.DateField(verbose_name='Data associazione')),
            ],
        ),
    ]
