# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Costo')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrizione')),
            ],
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Costo')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrizione')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('type', models.PositiveSmallIntegerField(verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cap',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='CAP non valido', regex='^\\d{5}$')], verbose_name='CAP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(default='VRFL', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Tessera non valida', regex='^VRFL\\d{5}$')], verbose_name='Tessera'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale_.Customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionale_.Event', verbose_name='Occasione'),
        ),
        migrations.AddField(
            model_name='processing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale_.Customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='gestionale_.Customer', verbose_name='Partecipanti'),
        ),
    ]
