# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale_.Customer', verbose_name='Cliente'),
        ),
    ]
