# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0002_auto_20170621_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterModelOptions(
            name='processing',
            options={'verbose_name': 'Lavorazione', 'verbose_name_plural': 'Lavorazioni'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Iscrizione', 'verbose_name_plural': 'Iscrizioni'},
        ),
    ]
