# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0002_auto_20170623_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Laser'), (1, 'Stampa3D'), (2, 'Fresa')], verbose_name='Tipo'),
        ),
    ]
