# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0003_auto_20170621_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'BASE'), (1, 'MAKER')], verbose_name='Tipo'),
        ),
    ]
