# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 21:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0004_auto_20170621_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(default='VRFL', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Tessera non valida', regex='^VRFL\\d{5}$')], verbose_name='Tessera'),
        ),
    ]
