# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 21:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0005_auto_20170621_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Numero di telefono non valido', regex='^[+]\\d{8,15}$')], verbose_name='Cellulare'),
        ),
    ]
