# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 22:56
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0007_auto_20170621_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_association',
            field=models.DateField(default=datetime.date.today, verbose_name='Data associazione'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(default='+39', max_length=17, validators=[django.core.validators.RegexValidator(message='Numero di telefono non valido', regex='^\\+?\\d{8,15}$')], verbose_name='Cellulare'),
        ),
    ]
