# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0008_auto_20170622_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale_.Customer', unique_for_year=models.DateField(default=datetime.date.today, verbose_name='Anno'), verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='year',
            field=models.DateField(default=datetime.date.today, verbose_name='Anno'),
        ),
    ]
