# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0009_auto_20170622_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionale_.Customer', unique_for_year='year', verbose_name='Cliente'),
        ),
    ]
