# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale_', '0010_auto_20170622_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Paypal'), (1, 'Bonifico'), (2, 'Contanti')], default=0, verbose_name='Pagamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Base'), (1, 'Maker')], verbose_name='Tipo'),
        ),
    ]
